### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by tkw1536** [KWARC/bibs#29]
We should move away from Travis and instead go to GitHub Actions; this is one of the few repos still using Travis.

**Comment by kohlhase** [comment]
I have (5 min ago) just "installed travis" for bibs on behest of Naivd, 
you should get into contact with him.

**Comment by tkw1536** [comment]
Already am, this is what caused the issue.

**Comment by kohlhase** [comment]
good.

**Comment by ComFreek** [comment]
I finally found out [due to a StackOverflow post](https://stackoverflow.com/a/41327657/603003) why the travis-ci.com builds had never been triggered. For the `KWARC` GitHub group there was no billing plan selected.
After selecting the "free billing plan" (as free as it sounds), the [first KWARC/bibs build after months is running again](https://app.travis-ci.com/github/KWARC/bibs/jobs/534547835) :smile:

**Comment by kohlhase** [comment]
Ah, very good. Thanks for keeping this on the burner.
