### ISSUE TITLE
only re-build the parts that have changes. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/bibs#9]
I have changed the Makefile so that only the parts XML files are rebuilt that need to be rebuilt. 
But the comparison mechanism when things should be built in travis  is not updated yet. 
Here is what should happen. 
kwarcpubs.bib --> rebuild kwarcpubs.bib.xml and pubs
extpubs.bib --> rebuild extpubs.bib.xml
kwarccrossrefs.bib --> rebuild kwarccrossrefs.bib.xml and pubs
extcrossrefs.bib -- rebuild extcrossrefs.bib.xml and pubs

**Comment by tkw1536** [comment]
With increased parallelism in https://github.com/KWARC/bibs/commit/5ac3142e82772f768095dd7e53f798b9612bb530, https://github.com/KWARC/bibs/commit/9cde85cc77fef3dd1434ce08253f2a1e5697d7a2 and https://github.com/KWARC/bibs/commit/4bbe62f9e93fdcc28fc98a1d417b9192353084e8 a full rebuild takes 15 - 20 minutes (towards the lower end). 
I no longer think this issue is required, closing.
